# Generated by Django 4.2.2 on 2023-08-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título brasileiro')),
                ('or_title', models.CharField(max_length=255, verbose_name='Título original')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author')),
                ('situation', models.CharField(blank=True, null=True, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Manga',
                'verbose_name_plural': 'Mangás',
                'ordering': ['pt_title'],
            },
        ),
        migrations.CreateModel(
            name='VolumeManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título brasileiro')),
                ('or_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título original')),
                ('number', models.BigIntegerField(verbose_name='Volume')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangas.manga', verbose_name='Mangá')),
            ],
            options={
                'verbose_name': 'Volume',
                'verbose_name_plural': 'Volume',
            },
        ),
        migrations.CreateModel(
            name='ChapterManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título brasileiro')),
                ('or_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título original')),
                ('number', models.BigIntegerField(verbose_name='Chapter')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangas.volumemanga', verbose_name='Volume')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
            },
        ),
    ]
