# Generated by Django 4.2.2 on 2023-08-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0002_alter_manga_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermanga',
            name='number',
            field=models.BigIntegerField(verbose_name='Capítulo'),
        ),
    ]
