# Generated by Django 4.2.2 on 2023-08-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0003_alter_chaptermanga_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermanga',
            name='number',
            field=models.FloatField(verbose_name='Capítulo'),
        ),
    ]
