# Generated by Django 4.2.2 on 2023-06-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='situation',
            field=models.CharField(blank=True, null=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título em Inglês'),
        ),
    ]
