# Generated by Django 4.2.7 on 2024-03-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_serie_modified_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episodeserie',
            unique_together={('number', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='seasonserie',
            unique_together={('number', 'serie')},
        ),
    ]
