# Generated by Django 4.2.2 on 2023-06-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_serie_situation_alter_serie_autor_alter_serie_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serie',
            options={'verbose_name': 'Série', 'verbose_name_plural': 'Séries'},
        ),
    ]
