# Generated by Django 4.2.2 on 2023-06-15 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_alter_serie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
