# Generated by Django 4.2.2 on 2023-06-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_serie_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='title_en',
        ),
        migrations.AddField(
            model_name='serie',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Diretor'),
        ),
        migrations.AddField(
            model_name='serie',
            name='or_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título original'),
        ),
    ]
