# Generated by Django 4.2.2 on 2023-06-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_remove_serie_autor_remove_serie_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serie',
            options={'ordering': ['created_at'], 'verbose_name': 'Série', 'verbose_name_plural': 'Séries'},
        ),
        migrations.AlterField(
            model_name='serie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em'),
        ),
    ]
