# Generated by Django 4.2.2 on 2023-06-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título brasileiro')),
                ('or_title', models.CharField(max_length=255, verbose_name='Título original')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author')),
                ('situation', models.CharField(blank=True, null=True, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
                'ordering': ['pt_title'],
            },
        ),
        migrations.CreateModel(
            name='SeasonAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título brasileiro')),
                ('or_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título original')),
                ('number', models.BigIntegerField(verbose_name='Temporada')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime', verbose_name='Anime')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
            },
        ),
        migrations.CreateModel(
            name='EpisodeAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título brasileiro')),
                ('or_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título original')),
                ('number', models.BigIntegerField(verbose_name='Episódio')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.seasonanime', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Episódio',
                'verbose_name_plural': 'Episódios',
            },
        ),
    ]
