# Generated by Django 4.2.2 on 2023-08-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Diretor'),
        ),
    ]
