# Generated by Django 4.2.2 on 2023-06-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='autor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movies',
            name='collection',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
