# Generated by Django 4.2.2 on 2023-06-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_autor_movies_collection_movies_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='collection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
