# Generated by Django 4.2.2 on 2023-06-15 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movies_autor_alter_movies_collection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['collection', 'title']},
        ),
    ]
