# Generated by Django 4.2.2 on 2023-06-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movies_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título em inglês')),
                ('autor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor')),
                ('collection', models.CharField(blank=True, max_length=255, null=True, verbose_name='Coleção')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'ordering': ['collection', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
