# Generated by Django 4.2.2 on 2023-06-15 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('serie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='series.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('season', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.season')),
            ],
        ),
    ]
