# Generated by Django 4.2.2 on 2023-06-15 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_alter_serie_options'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name': 'Episódio', 'verbose_name_plural': 'Episódios'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Temporada', 'verbose_name_plural': 'Temporadas'},
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.season', verbose_name='Temporada'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Episódio'),
        ),
        migrations.AlterField(
            model_name='season',
            name='serie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='series.serie', verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='season',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Temporada'),
        ),
    ]
