# Generated by Django 4.2.2 on 2023-06-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userepisode_options_alter_usermovie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='numero',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Número do episódio'),
        ),
    ]
