# Generated by Django 4.2.2 on 2023-06-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_episode_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='numero',
            new_name='number',
        ),
    ]
