# Generated by Django 4.2.2 on 2023-06-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_numero_episode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Episódio'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título'),
        ),
    ]
