# Generated by Django 4.2.2 on 2023-06-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='episodes',
            field=models.ManyToManyField(blank=True, through='core.UserEpisode', to='core.episode'),
        ),
        migrations.AddField(
            model_name='user',
            name='movies',
            field=models.ManyToManyField(blank=True, through='core.UserMovie', to='movies.movie'),
        ),
    ]
