# Generated by Django 4.2.2 on 2023-06-29 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
        ('series', '0001_initial'),
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userepisodeanime',
            options={'verbose_name': 'Episódio de anime', 'verbose_name_plural': 'Episódios de animes'},
        ),
        migrations.AlterModelOptions(
            name='userepisodeserie',
            options={'verbose_name': 'Episódio de série', 'verbose_name_plural': 'Episódios de séries'},
        ),
        migrations.AlterModelOptions(
            name='usermovie',
            options={'verbose_name': 'Filme do Usuário', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AlterField(
            model_name='userepisodeanime',
            name='date_watched',
            field=models.DateTimeField(verbose_name='Assistido em'),
        ),
        migrations.AlterField(
            model_name='userepisodeanime',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.episodeanime', verbose_name='Episódio'),
        ),
        migrations.AlterField(
            model_name='userepisodeanime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='userepisodeserie',
            name='date_watched',
            field=models.DateTimeField(verbose_name='Assistido em'),
        ),
        migrations.AlterField(
            model_name='userepisodeserie',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.episodeserie', verbose_name='Episódio'),
        ),
        migrations.AlterField(
            model_name='userepisodeserie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='date_watched',
            field=models.DateTimeField(verbose_name='Assistido em'),
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Filme'),
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='userepisodeanime',
            unique_together={('user', 'episode')},
        ),
        migrations.AlterUniqueTogether(
            name='userepisodeserie',
            unique_together={('user', 'episode')},
        ),
        migrations.AlterUniqueTogether(
            name='usermovie',
            unique_together={('user', 'movie')},
        ),
    ]
