# Generated by Django 4.2.2 on 2023-08-07 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author'),
        ('mangas', '0003_alter_chaptermanga_number'),
        ('accounts', '0002_alter_userepisodeanime_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChapterManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_watched', models.DateTimeField(verbose_name='Lido em')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangas.chaptermanga', verbose_name='Capítulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Capítulo de mangá',
                'verbose_name_plural': 'Capítulos de mangás',
                'unique_together': {('user', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_watched', models.DateTimeField(verbose_name='Lido em')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Livro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Livro do usuário',
                'verbose_name_plural': 'Livros do usuários',
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(blank=True, through='accounts.UserBook', to='books.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='chapters_manga',
            field=models.ManyToManyField(blank=True, through='accounts.UserChapterManga', to='mangas.chaptermanga'),
        ),
    ]
