# Generated by Django 4.2.2 on 2023-08-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userchaptermanga_userbook_user_books_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbook',
            options={'verbose_name': 'Livro do usuário', 'verbose_name_plural': 'Livros'},
        ),
    ]
