# Generated by Django 4.2.2 on 2023-08-31 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author'),
        ('series', '0002_serie_modified_at'),
        ('animes', '0003_alter_anime_author'),
        ('mangas', '0004_alter_chaptermanga_number'),
        ('movies', '0002_movie_director'),
        ('accounts', '0004_alter_userbook_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.serie', verbose_name='Série')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Série favorita',
                'verbose_name_plural': 'Séries favoritas',
                'unique_together': {('user', 'serie')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Filme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Filme favorito',
                'verbose_name_plural': 'Filmes favoritos',
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangas.manga', verbose_name='Mangá')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Mangá favorito',
                'verbose_name_plural': 'Mangás favoritos',
                'unique_together': {('user', 'manga')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Livro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Livro favorito',
                'verbose_name_plural': 'Livros favoritos',
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime', verbose_name='Anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Anime favorito',
                'verbose_name_plural': 'Animes favoritos',
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
