# Generated by Django 4.2.7 on 2023-11-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_favoriteserie_favoritemovie_favoritemanga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'favorites_view',
                'managed': False,
            },
        ),
    ]
