# Generated by Django 4.2.2 on 2023-08-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor'),
        ),
    ]
