# Generated by Django 4.2.2 on 2023-08-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título brasileiro')),
                ('or_title', models.CharField(max_length=255, verbose_name='Título original')),
                ('resume', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Resumo')),
                ('collection', models.CharField(blank=True, max_length=255, null=True, verbose_name='Coleção')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Ano')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['pt_title'],
            },
        ),
    ]
