# Generated by Django 4.2.2 on 2023-08-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='modified_at',
            field=models.DateField(auto_now=True, verbose_name='Modificado em'),
        ),
    ]
