# Generated by Django 4.2.2 on 2023-07-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='modified_at',
            field=models.DateField(auto_now=True, verbose_name='Modificado em'),
        ),
    ]
