# Generated by Django 4.2.7 on 2023-11-24 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_alter_anime_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonanime',
            options={'ordering': ['anime__or_title', 'number'], 'verbose_name': 'Temporada', 'verbose_name_plural': 'Temporadas'},
        ),
    ]
