# Generated by Django 4.2.7 on 2024-07-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_alter_seasonanime_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seasonanime',
            unique_together={('number', 'anime')},
        ),
    ]
